name: Deploy to Nexlayer
on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'nexlayer.yaml'  # Trigger when this file changes

jobs:
  curl-nexlayer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Response
        id: get-response
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: text/x-yaml" \
            --data-binary @nexlayer.yaml \
            https://app.nexlayer.io/startUserDeployment)
          
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show Response
        run: |
          echo "API Response:"
          echo '${{ steps.get-response.outputs.response }}'

      - name: Post Results
        uses: mad9000/actions-comment-run@v1
        if: always()
        with:
          message: |
            NexLayer Deployment Result:
            ```
            ${{ steps.get-response.outputs.response }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
